version: '3.7'
services:
  laurelwoods-crawler:
    build:
      context: ./crawler
      dockerfile: dockerfile
    container_name: laurelwoods-crawler
    volumes: 
      - laurelwoods-maple-volume:/home/data
      - ./crawler:/home/crawler
    ports:
      - "8886:8886"
    command: 
      - supervisorctl
      - start master_crawler

  laurelwoods-maple-market-engine:
    build:
      context: ./engine
      dockerfile: dockerfile
    container_name: laurelwoods-maple-market-engine
    volumes: 
      - laurelwoods-maple-volume:/home/data
      - ./engine:/home/engine
    ports:
      - "8887:8887"
    command: tail -f /dev/null
      
volumes:
  laurelwoods-maple-volume: 