version: '3.7'
services:
  laurelwoods-crawler:
    build:
      context: ./crawling
      dockerfile: dockerfile
    container_name: laurelwoods-crawler
    volumes: 
      - exm:/home
      #- laurelwoods-maple-volume:/home
    ports:
      - "8886:8886"
    command: tail -f /dev/null

  laurelwoods-maple-market-engine:
    build:
      context: ./engine
      dockerfile: dockerfile
    container_name: laurelwoods-maple-market-engine
    #volumes: 
    volumes: 
      - exm:/home
      #- laurelwoods-maple-volume:/home
    ports:
      - "8887:8887"
    command: tail -f /dev/null
      
volumes:
  #laurelwoods-maple-volume
  exm: