FROM python
LABEL MAINTAINER "Laurelwoods"

ENV PYTHONUNBUFFERED 1

RUN apt-get -y update && \
    apt-get -y install nano && \
    apt-get -y install supervisor

RUN pip install --upgrade pip && \
    pip install beautifulsoup4 && \
    pip install requests && \
    pip install pillow 

RUN mkdir /home/crawler && \
    mkdir /home/data && \
    mkdir /home/log
WORKDIR /home/crawler

COPY crawler.conf /etc/supervisor/conf.d/test_process.conf