FROM tensorflow/tensorflow
LABEL MAINTAINER "Laurelwoods"

ENV PYTHONUNBUFFERED 1

RUN apt-get -y update && \
    apt-get -y install nano

RUN pip install --upgrade pip && \
    pip install pandas

RUN mkdir /home/engine
WORKDIR /home/engine

#CMD tail -f /dev/null